apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jitensingh-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus@sha256:93b6334f608f7ed0478941d8b8a4763ccc9b37c2aae2768e83b4aaa3da042cb6
        name: my-java-quarkus
        resources: {}
status: {}
